### ISSUE TITLE
conflicting instructions on dropping null columns/rows

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-categorical-variables-regression-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6536/assignments/241395?module_item_id=567615

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

Code cell three has markdown instructions right above it saying "Go ahead and drop all columns with missing data..." but the comment in the code cell says to "drop rows with missing data."
```
# Your code here - drop rows with missing data
```

### Concern

Conflicting directions.

## (Optional) Proposed Solution

I think you mean to say to drop the columns with NaNs, not the rows.

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [x] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
You are correct. Thank you for letting us know. Fixed.
